# Generated by Django 5.2.15 on 2026-09-28 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resumes/', verbose_name='الملف')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='اسم الملف')),
                ('parsed_text', models.TextField(blank=True, default='', verbose_name='النص المستخرج')),
                ('doc_embedding', models.TextField(blank=True, default='')),
                ('chunk_embeddings', models.TextField(blank=True, default='')),
                ('parse_status', models.CharField(choices=[('pending', 'قيد المعالجة'), ('done', 'تمت المعالجة'), ('failed', 'فشلت المعالجة')], default='pending', max_length=10, verbose_name='حالة المعالجة')),
                ('parse_error', models.TextField(blank=True, default='', verbose_name='سبب الفشل')),
                ('is_active', models.BooleanField(default=False, verbose_name='السيرة المعتمدة')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='accounts.seekerprofile', verbose_name='الباحث عن عمل')),
            ],
            options={
                'verbose_name': 'سيرة ذاتية',
                'verbose_name_plural': 'السير الذاتية',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
