# Generated by Django 5.2.15 on 2026-09-29 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('applications', '0001_initial'),
        ('jobs', '0002_alter_job_required_skills'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('applied', 'تم التقديم'), ('screening', 'الفرز المبدئي'), ('interview', 'المقابلة'), ('offer', 'عرض وظيفي'), ('hired', 'تم التوظيف'), ('rejected', 'مرفوض')], default='applied', max_length=20, verbose_name='المرحلة')),
                ('match_score', models.FloatField(default=0.0, verbose_name='النتيجة النهائية')),
                ('semantic_score', models.FloatField(default=0.0, verbose_name='التشابه العام')),
                ('coverage_score', models.FloatField(default=0.0, verbose_name='تغطية المهارات')),
                ('skill_results', models.TextField(blank=True, default='')),
                ('cover_letter', models.TextField(blank=True, verbose_name='رسالة التقديم')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقديم')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job', verbose_name='الوظيفة')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='applications.resume', verbose_name='السيرة الذاتية')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.seekerprofile', verbose_name='المتقدم')),
            ],
            options={
                'verbose_name': 'طلب توظيف',
                'verbose_name_plural': 'طلبات التوظيف',
                'ordering': ['-match_score', '-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='RecruiterNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='الملاحظة')),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='اختياري، من 1 إلى 5.', null=True, verbose_name='التقييم')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='applications.application', verbose_name='الطلب')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruiter_notes', to=settings.AUTH_USER_MODEL, verbose_name='الكاتب')),
            ],
            options={
                'verbose_name': 'ملاحظة',
                'verbose_name_plural': 'الملاحظات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stage', models.CharField(blank=True, choices=[('applied', 'تم التقديم'), ('screening', 'الفرز المبدئي'), ('interview', 'المقابلة'), ('offer', 'عرض وظيفي'), ('hired', 'تم التوظيف'), ('rejected', 'مرفوض')], max_length=20, verbose_name='من مرحلة')),
                ('to_stage', models.CharField(choices=[('applied', 'تم التقديم'), ('screening', 'الفرز المبدئي'), ('interview', 'المقابلة'), ('offer', 'عرض وظيفي'), ('hired', 'تم التوظيف'), ('rejected', 'مرفوض')], max_length=20, verbose_name='إلى مرحلة')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='applications.application', verbose_name='الطلب')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_changes', to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
            ],
            options={
                'verbose_name': 'سجل المراحل',
                'verbose_name_plural': 'سجل المراحل',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('job', 'seeker'), name='unique_application'),
        ),
    ]
