# Generated by Django 5.2.15 on 2026-09-28 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='المسمى الوظيفي')),
                ('description', models.TextField(verbose_name='وصف الوظيفة')),
                ('required_skills', models.TextField(help_text='مهارة واحدة في كل سطر، وتُكتب بالإنجليزية. العبارات الكاملة أدق من الكلمات المفردة: اكتب «3+ years of React development» بدلًا من «React».', verbose_name='المهارات المطلوبة')),
                ('location', models.CharField(help_text='مثال: الخرطوم، أم درمان، بورتسودان.', max_length=200, verbose_name='المدينة')),
                ('employment_type', models.CharField(choices=[('full_time', 'دوام كامل'), ('part_time', 'دوام جزئي'), ('contract', 'عقد مؤقت'), ('internship', 'تدريب'), ('remote', 'عمل عن بعد')], default='full_time', max_length=20, verbose_name='نوع التوظيف')),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='أقل راتب (ج.س)')),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='أعلى راتب (ج.س)')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('open', 'مفتوحة'), ('closed', 'مغلقة')], default='draft', max_length=10, verbose_name='الحالة')),
                ('description_embedding', models.TextField(blank=True, default='')),
                ('skills_embedding', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.companyprofile', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'وظيفة',
                'verbose_name_plural': 'الوظائف',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='jobs.job', verbose_name='الوظيفة')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to='accounts.seekerprofile', verbose_name='الباحث عن عمل')),
            ],
            options={
                'verbose_name': 'وظيفة محفوظة',
                'verbose_name_plural': 'الوظائف المحفوظة',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('seeker', 'job'), name='unique_saved_job')],
            },
        ),
    ]
