# Generated by Django 5.2.15 on 2026-09-28 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='required_skills',
            field=models.TextField(help_text='مهارة واحدة في كل سطر، وتُكتب بالإنجليزية. صِف العمل نفسه لا سنوات الخبرة: عبارة مثل «building REST APIs with Django and Python» تعطي تطابقًا أدق بكثير من «Python» وحدها، بينما «3+ years of Python» تُطابق سطور المؤهلات الدراسية بدلًا من سطور الخبرة العملية.', verbose_name='المهارات المطلوبة'),
        ),
    ]
